# Generated by Django 2.2 on 2020-01-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oui',
            fields=[
                ('domain_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=30)),
                ('force_max_age', models.CharField(blank=True, max_length=255, null=True)),
                ('rewrite_url', models.CharField(blank=True, max_length=255, null=True)),
                ('gzip_compressed', models.CharField(blank=True, max_length=1, null=True)),
                ('sam', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oui',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField(blank=True, null=True)),
                ('domain_id', models.IntegerField(blank=True, null=True)),
                ('ok', models.CharField(blank=True, max_length=1, null=True)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
                ('param', models.CharField(blank=True, max_length=255, null=True)),
                ('status_code', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'url',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('passwd', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
